
spring:
  datasource:
    url: jdbc:mysql://47.93.76.253:3306/warehouse?serverTimezone=UTC&useSSL=false
    username: warehouse
    password: kAtfxNsBiGSTdkKA
    driver-class-name: com.mysql.jdbc.Driver

